# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    view:
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
        - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    body_converter:
        enabled: true
    param_fetcher_listener: true

